apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: contract-listener
  name: contract-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contract-listener
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: contract-listener
    spec:
      containers:
        - env:
          image: gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/contract-listener
          livenessProbe:
            exec:
              command:
                - curl -sS http://127.0.0.1 || exit 1
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 10
          name: contract-listener
          resources: {}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10m"]
          volumeMounts:
            - mountPath: /data
              name: stream-data
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      volumes:
        - name: stream-data
          persistentVolumeClaim:
            claimName: stream-data
status: {}
