apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chess-wager-backend-server
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:progressDeadlineSeconds": {}
          "f:replicas": {}
          "f:revisionHistoryLimit": {}
          "f:selector": {}
          "f:strategy":
            "f:rollingUpdate":
              .: {}
              "f:maxSurge": {}
              "f:maxUnavailable": {}
            "f:type": {}
          "f:template":
            "f:metadata":
              "f:labels":
                .: {}
                "f:app": {}
            "f:spec":
              "f:containers":
                'k:{"name":"chesswager-1"}':
                  .: {}
                  "f:image": {}
                  "f:imagePullPolicy": {}
                  "f:name": {}
                  "f:resources": {}
                  "f:terminationMessagePath": {}
                  "f:terminationMessagePolicy": {}
              "f:dnsPolicy": {}
              "f:restartPolicy": {}
              "f:schedulerName": {}
              "f:securityContext": {}
              "f:terminationGracePeriodSeconds": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2021-11-25T15:51:01Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:deployment.kubernetes.io/revision": {}
        "f:status":
          "f:conditions":
            .: {}
            'k:{"type":"Available"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"Progressing"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:observedGeneration": {}
          "f:replicas": {}
          "f:unavailableReplicas": {}
          "f:updatedReplicas": {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-11-25T15:58:14Z"
  name: chess-wager-backend-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-wager-backend-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chess-wager-backend-server
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - image: gcr.io/chess-wager-main/github.com/geektechniquestudios/chesswager
          imagePullPolicy: IfNotPresent
          name: chesswager-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: chess-wager-backend-server
  managedFields:
    - apiVersion: autoscaling/v2beta1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:maxReplicas": {}
          "f:metrics": {}
          "f:minReplicas": {}
          "f:scaleTargetRef":
            "f:apiVersion": {}
            "f:kind": {}
            "f:name": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2021-11-25T15:51:01Z"
    - apiVersion: autoscaling/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:autoscaling.alpha.kubernetes.io/conditions": {}
            "f:autoscaling.alpha.kubernetes.io/current-metrics": {}
        "f:status":
          "f:currentReplicas": {}
          "f:desiredReplicas": {}
      manager: vpa-recommender
      operation: Update
      time: "2021-11-25T15:51:17Z"
  name: chess-wager-backend-server-hpa-i2dm
  namespace: default
spec:
  maxReplicas: 1
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chess-wager-backend-server
